apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: manna-assignment
  name: manna-assignment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: manna-assignment
status:
  loadBalancer: {}
