apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: manna-assignment
  name: manna-assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manna-assignment
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manna-assignment
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/rishhabhhanday-dev/manna-assignment
          name: manna-assignment
          resources: { }
status: { }
